Update latest GitLab4.x, with sidekiq

diff --git a/gitlab/gitlabd b/gitlab/gitlabd
--- a/gitlab/gitlabd
+++ b/gitlab/gitlabd
@@ -1,4 +1,10 @@
 #! /bin/bash
+
+# GITLAB
+# Maintainer: @randx
+# App Version: 4.0
+# After https://github.com/gitlabhq/gitlab-recipes/blob/master/init.d/gitlab
+
 ### BEGIN INIT INFO
 # Provides:          gitlab
 # Required-Start:    $local_fs $remote_fs $network $syslog redis-server
@@ -9,42 +15,120 @@
 # Description:       GitLab git repository management
 ### END INIT INFO
 
-DAEMON_OPTS="-c ${H}/gitlab/github/config/unicorn.rb -E production -D"
-NAME=unicorn
+
+APP_ROOT="${H}/gitlab/github"
+START_DAEMON_PROCESS="bundle exec unicorn_rails $DAEMON_OPTS"
+DAEMON_OPTS="-c $APP_ROOT/config/unicorn.rb -E production"
+PID_PATH="$APP_ROOT/tmp/pids"
+UNICORN_PID="$PID_PATH/unicorn.pid"
+SIDEKIQ_PID="$PID_PATH/sidekiq.pid"
+STOP_SIDEKIQ="RAILS_ENV=production bundle exec rake sidekiq:stop"
+START_SIDEKIQ="RAILS_ENV=production bundle exec rake sidekiq:start"
+NAME="unicorn"
 DESC="Gitlab service"
-PID="${H}/gitlab/github/tmp/pids/unicorn.pid"
-RESQUE_PID="${H}/gitlab/github/tmp/pids/resque_worker.pid"
+CD_TO_APP_ROOT="cd ${APP_ROOT}"
+
+check_pid(){
+
+  if [ -f $UNICORN_PID ]; then
+    PID=`cat $UNICORN_PID`
+    SPID=`cat $SIDEKIQ_PID`
+    echo "ps aux | grep $PID | grep -v grep | wc -l"
+    STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
+  else
+    STATUS=0
+    PID=0
+  fi
+}
+
+start() {
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    # Program is running, exit with error code 1.
+    echo "Error! $DESC $NAME is currently running!"
+    exit 1
+  else
+    echo "Starting $DESC: "
+    #echo "${CD_TO_APP_ROOT} > ${H}/gitlab/logs/start.log 2>&1 && mkdir -p $PID_PATH && $START_DAEMON_PROCESS && $START_SIDEKIQ" 
+    #${CD_TO_APP_ROOT} > "${H}/gitlab/logs/start.log" 2>&1 && mkdir -p $PID_PATH && $START_DAEMON_PROCESS && $START_SIDEKIQ 
+    echo "nohup bundle exec unicorn_rails $DAEMON_OPTS  > /dev/null  2>&1 &"
+    echo "mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &"
+    #nohup bundle exec unicorn_rails $DAEMON_OPTS  > /dev/null  2>&1 &
+    #mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &
+    echo "$DESC started"
+  fi
+}
+
+stop() {
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    ## Program is running, stop it.
+    kill -QUIT `cat $UNICORN_PID`
+    mkdir -p $PID_PATH && $STOP_SIDEKIQ
+    rm "$UNICORN_PID" >> /dev/null
+    echo "$DESC stopped"
+  else
+    ## Program is not running, exit with error.
+    echo "Error! $DESC not started!"
+    exit 1
+  fi
+}
+
+restart() {
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    echo "Restarting $DESC..."
+    kill -USR2 `cat $UNICORN_PID`
+    mkdir -p $PID_PATH && $STOP_SIDEKIQ && $START_SIDEKIQ 
+    echo "$DESC restarted."
+  else
+    echo "Error, $NAME not running!"
+    exit 1
+  fi
+}
+
+status() {
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    echo "$DESC / Unicorn with PID $PID is running."
+    echo "$DESC / Sidekiq with PID $SPID is running."
+  else
+    echo "$DESC is not running."
+    exit 1
+  fi
+}
+
+## Check to see if we are running as root first.
+## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
+#if [ "$(id -u)" != "0" ]; then
+#    echo "This script must be run as root"
+#    exit 1
+#fi
 
 case "$1" in
   start)
-        CD_TO_APP_DIR="cd ${H}/gitlab/github"
-        START_DAEMON_PROCESS="bundle exec unicorn_rails $DAEMON_OPTS"
-        START_RESQUE_PROCESS="./resque.sh"
-
-        echo -n "Starting $DESC: "
-        $CD_TO_APP_DIR > "${H}/gitlab/logs/start.log" 2>&1 && $START_DAEMON_PROCESS && $START_RESQUE_PROCESS
-        echo "$NAME."
+        start
         ;;
   stop)
-        echo -n "Stopping $DESC: "
-        kill -QUIT `cat $PID`
-        kill -QUIT `cat $RESQUE_PID`
-        echo "$NAME."
+        stop
         ;;
   restart)
-        echo -n "Restarting $DESC: "
-        kill -USR2 `cat $PID`
-        kill -USR2 `cat $RESQUE_PID`
-        echo "$NAME."
+        restart
         ;;
-  reload)
-        echo -n "Reloading $DESC configuration: "
+  reload|force-reload)
+        echo -n "Reloading $NAME configuration: "
         kill -HUP `cat $PID`
-        kill -HUP `cat $RESQUE_PID`
-        echo "$NAME."
+        echo "done."
+        ;;
+  status)
+        status
         ;;
   *)
-        echo "Usage: $NAME {start|stop|restart|reload}" >&2
+        echo "Usage: sudo service gitlab {start|stop|status|restart|reload}" >&2
         exit 1
         ;;
 esac
