Php Composer tool, Php and GitList fixes
M  .gitignore:
  Ignore 'php/composer'
M  .cpl/_deps:
  Add 'Composer' (php) module
M  .cpl/params/php:
  Calls the right name in post
M  gitlist/install_or_update_gitlist.sh:
  Fix syntax errors
  Add 'Composer install/update' step
A  php/composer/composer:
  Composer command
A  php/composer/install_or_update:
  Add 'Composer' to '${H}/bin'
R  php/post_install_php -> php/post_install
  RENAMED post_install step for php

diff --git a/php/post_install b/php/post_install
--- a/php/post_install
+++ b/php/post_install
@@ -4,6 +4,8 @@ if [[ ! -e "${H}/apache/apache2/modules/libphp5.so" ]] ; then
   if [[ -e "${H}/.cpl/src/php/libs/libphp5.so" ]] ; then
     cp "${H}/.cpl/src/php/libs/libphp5.so" "${H}/apache/apache2/modules/"
   else
+    echo -e "\e[1;31mERROR --- '${H}/.cpl/src/php/libs/libphp5.so' is MISSING\e[0m" 1>&2
+    exit 1
   fi
 fi
 
